{
    "name": "Reservations Clients & Encaissements",
    "summary": "Reservations de stock client avec encaissements operationnels",
    "version": "19.0.1.2.0",
    "category": "Inventory/Inventory",
    "author": "Extreme Ceramique",
    "license": "LGPL-3",
    "icon": "/stock_customer_reservation_cash/static/description/icon_v2.png",
    "images": ["static/description/icon_v2.png"],
    "depends": ["stock", "account", "mail", "sale_management", "sale_stock"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
        "data/sequences.xml",
        "data/legacy_menu_cleanup.xml",
        "views/sale_reservation_views.xml",
         "views/cash_in_views.xml",
        "views/sale_order_v2_views.xml",
        "views/payment_mode_views.xml",
        "views/res_partner_views.xml",
        "views/warehouse_views.xml",
        "views/delivery_contact_wizard_views.xml",
        "views/sale_cancel_reservation_cash_wizard_views.xml",
        "views/menus.xml",
    ],
    "application": True,
    "installable": True,
}
